# Generated by Django 3.0.4 on 2020-04-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(default='Not Found', max_length=1000, null=True),
        ),
    ]
